version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id pinaka-rds-secret --region ap-south-1 | jq -r '.SecretString')
        export DB_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.password')
        export DB_USERNAME=$(echo "$SECRET_JSON" | jq -r '.username')
        export DB_HOST=$(echo "$SECRET_JSON" | jq -r '.host')
        export DB_PORT=$(echo "$SECRET_JSON" | jq -r '.port')
        export DB_NAME=$(echo "$SECRET_JSON" | jq -r '.dbname')
        # Update application.properties file with the retrieved values
        sed -i "s|jdbc.password=admin123|jdbc.password=$DB_PASSWORD|" src/main/resources/application.properties
        sed -i "s|jdbc.username=admin|jdbc.username=$DB_USERNAME|" src/main/resources/application.properties
        sed -i "s|db01:3306|$DB_HOST:$DB_PORT|" src/main/resources/application.properties

  build:
    commands:
      - mvn install

  post_build:
    commands:
      - mvn package

artifacts:
  files:
    - '**/*'
  base-directory: 'target/vprofile-v2'
